### ISSUE TITLE
Boss support doesn't work 1.13.1

### ISSUE THREAD

**Issue by RegencySolid** [kangarko/CoreArena#135] opened 2018-09-17 21:44 UTC
as stated in the title, Boss mob eggs dont work with spawn points

**Comment by kangarko** [comment] 2018-09-27 18:01
Just testing but could not reproduce, any errors? Are the eggs there or they disappear when you reopen the menu?

Make sure to run very latest of CA + Boss.

Set Debug to [spawning] in settings.yml and report back the messages.

**Comment by kangarko** [comment] 2018-10-05 18:42
Closing, comment below if still having issues

**Closed by kangarko** 2018-10-05 18:42 UTC
Labels: Issue: complaint
