### ISSUE TITLE
1.12.2: Placeholder for PlaceholderAPI not work

### ISSUE THREAD

**Issue by SskyWorms** [kangarko/CoreArena#295] opened 2020-03-07 14:03 UTC
So, i try parse all placeholder variables in https://github.com/kangarko/CoreArena/wiki/PlaceholderAPI
but all of that not work in my server 
my PlaceholderAPI is 2.10.4
my CoreArena is 2.5.9
This is image
![image](https://user-images.githubusercontent.com/54969382/76144880-022ce600-60b7-11ea-8a6c-fe2ea454058a.png)

**Comment by JavaFactoryDev** [comment] 2020-03-07 16:53
HI SskyWorms,

we will have a look soon:)

Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment] 2020-03-09 17:06
Can you please send us your corearena.zip & the output of the startup when you set the debug-section in the config to Debug: ['*'].

**Comment by SskyWorms** [comment] 2020-03-14 02:21
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/4332207/CoreArena.zip)

**Comment by SskyWorms** [comment] 2020-03-14 02:22
[latest.log](https://github.com/kangarko/CoreArena/files/4332209/latest.log)

**Comment by lackoSK** [comment] 2020-03-16 18:51
Hi there, as far I know placeholderapi takes %%placeholder%% not {} or %

**Comment by SskyWorms** [comment] 2020-03-17 02:32
> Hi there, as far I know placeholderapi takes %%placeholder%% not {} or %

Not work /papi parse me %%corearena_nuggets%% return to %%corearena_nuggets%%

**Comment by JavaFactoryDev** [comment] 2020-03-21 17:54
Can you tell me whether this is fixed with the latest version, please

**Comment by JavaFactoryDev** [comment] 2020-03-25 12:33
Fixed

**Comment by SskyWorms** [comment] 2020-03-26 09:34
still not work

**Comment by JavaFactoryDev** [comment] 2020-03-28 12:41
Yeah, this is caused by changes in the PlaceholderAPI.
We will fix it.

**Comment by kangarko** [comment] 2020-05-11 04:51
@JavaFactoryDev is this fixed?

**Comment by JavaFactoryDev** [comment] 2020-05-21 10:46
Works fine on the latest version.

**Closed by JavaFactoryDev** 2020-05-21 10:46 UTC
