### ISSUE TITLE
Game Auto Ends

### ISSUE THREAD

**Issue by MagicPenguin720** [kangarko/CoreArena#274] opened 2020-02-15 08:07 UTC
Currently in Minecraft version 1.15.2 and I'm running the latest version of CoreArena. I set up the arena right and when its time to join the arena. I get moved into the lobby, wait the 30 seconds once I leave the lobby it takes me back to my server spawn and says game over. I've tried other visions and I have the same problem with them and some versions when I join the arena they will time me out.

**Comment by JavaFactoryDev** [comment] 2020-02-15 08:53
Please follow #275

**Comment by MagicPenguin720** [comment] 2020-02-15 15:08
[](url)

**Comment by MagicPenguin720** [comment] 2020-02-15 15:24
> Please follow #275

Here is a copy of my server files. Its a google drive link to download because its to big for me to upload on here. (It is a compressed folder)
https://drive.google.com/drive/folders/1piHZ3Fieugvepw0w64g8EUYFm5hLel5k?usp=sharing

**Comment by MagicPenguin720** [comment] 2020-02-15 17:03
I have found more problems I will list them down below.
1. When I join the arena it removes the whole arena. Which means the arena blocks and everything disappears. 
2. Every time I join an arena the server freezes.

**Comment by JavaFactoryDev** [comment] 2020-02-16 14:31
Hey, MagicPenguin720

Thank for using CoreArena and taking the time to report this issue.
We will have a look soon.

P.S. Please don't upload the boss.jar

Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment] 2020-02-16 14:33
It seems like this error has something to do with the outdated version of Boss you use, can you try updating?

**Comment by MagicPenguin720** [comment] 2020-02-16 16:26
I've installed the latest version of boss 3.6.8 but the Mob Arena is still Auto Ending. In the google drive link I've uploaded updated server files. The zip is called TownyServer.zip
Also if you want I can make a quick video on this and give you the link.

**Comment by JavaFactoryDev** [comment] 2020-02-20 13:21
Hey MagicPenguin720,

We hope that the issue is fixed with the latest version of CoreArena.

Regards,
- Leonhard

**Closed by JavaFactoryDev** 2020-02-20 13:21 UTC

**Comment by MagicPenguin720** [comment] 2020-02-21 20:18
The mob arena still auto ends

**Comment by kangarko** [comment] 2020-05-11 04:47
@JavaFactoryDev missed this?
