### ISSUE TITLE
Lands Integration Issue

### ISSUE THREAD

**Issue by vaznokk** [kangarko/CoreArena#307] opened 2020-04-28 15:17 UTC
Server Version: 1.15.2 PaperMC
How to recreate: Starting the server with Lands and CoreArena Enabled
Server log: https://pastebin.com/XkYUZWFX
It seems to be loading the LandsApi integration, then failing. I'm assuming its a CoreArena issue because it occurs on CA's startup and the plugin itself is loading it. 

I don't see any reason these to plugins would have compatibility issues, unless its to do with WorldGuard/WorldEdit? I haven't changed any settings yet because I can't even get the plugin to load.
Im on the latest version of both Lands and CoreArena.
https://www.spigotmc.org/resources/lands-minecraft-land-claim-plugin-grief-prevention-protection-gui-management-wars-1-15-support.53313/

**Comment by kangarko** [comment] 2020-05-11 04:59
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment] 2020-05-11 19:37
Hey vaznokk,

Reporting this issue here.

It seems like this is an issue caused by an integration made by @lackoSK 
I will ask him to have a look.

Regards
Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment] 2020-05-21 10:53
Fixed with 2.6.2

**Closed by JavaFactoryDev** 2020-05-21 10:53 UTC
