### ISSUE TITLE
White Signs & Empty Chests on WorldEdit Snapshot Load

### ISSUE THREAD

**Issue by JimBridger** [kangarko/CoreArena#171] opened 2019-01-23 21:43 UTC
So the issue is exactly as the title suggests the signs all appear when a game is started and if you right click them you can buy the item, however, you can't read the sign to see what you're purchasing lol, there are no words showing up.

And as for the chests, I've set them to refill every 3 phases, filled them, taken the snapshot, started the game, but the chests are never filled.  I know I'm missing something, but I can't figure it out.

Neither issue gives me any errors in console.

As per your previous guidance, I've updated to the latest worldedit snapshot and am using FastAsyncWorldEdit.
Thank you or your help!!

Respectfully,

Jim

**Comment by kangarko** [comment] 2019-01-26 11:14
Hey, please ZIP me your CoreArena plugin folder for debug

**Comment by JimBridger** [comment] 2019-01-26 18:30
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/2799357/CoreArena.zip)
MC version: 1.13.2

**Comment by kangarko** [comment] 2019-02-10 11:40
Apology for not getting back to you sooner. As a compensation I offer you 1 premium resource of mine for free, just let me know Spigot username below.

**#1 Blank signs in arena**
I confirmed this problem and opened a ticket on WorldEdit's side, https://dev.enginehub.org/youtrack/issue/WORLDEDIT-3847, will check it out soonest they reply

#2 Empty chests / not being filled
This seems to relate to the first problem since the chests are placed empty when the arena starts. We only scan them after that and refill to what has been in them at the start. I added a comment to the WorldEdit's ticket above.

I hope we get this resolved soon.

**Comment by kangarko** [comment] 2019-02-19 13:48
Will be fixed in the next version

**Closed by kangarko** 2019-02-19 13:48 UTC
Labels: Issue: confirmed, Status: in progress

**Comment by JimBridger** [comment] 2019-02-20 18:25
great thank you!  I look forward to this!  there's no need to compensate me, I believe I already own all of your paid plugins.

**Comment by kangarko** [comment] 2019-02-21 11:40
<3
