### ISSUE TITLE
Minecraft 1.21.1 Paper v57

### ISSUE THREAD

**Issue by cobrex1** [kangarko/CoreArena#536] opened 2024-09-09 19:19 UTC
Relating to Core Arena 3.9.9 and Boss 4.13.8

2) Be clear: What is your current situation, the desired situation, and your problem?
Bosses spawning from the area spawn points are not Boss monster from the Boss plugin, they are normal zombies for example. They have no armour, Boss names nor Boss drops when killed.

I have checked the spawn points with the arena edit tools and the spawn point shows the correct boss egg.

This is happening in all the areas that I have set up with CoreArena
There are no errors in console from startup

**Comment by kangarko** [comment] 2024-09-09 19:41
Assuming you used the latest build from today?

**Comment by kangarko** [comment] 2024-09-09 19:42
Investigating in 1-2 days

**Comment by kangarko** [comment] 2024-09-10 06:06
I am almost ready pushing the new corearena based off of foundation 7, mind waiting a few extra days?

**Comment by cobrex1** [comment] 2024-09-12 05:15
I can see all the work you are doing on Foundation 7. Depends on what you mean by 'a few days'. I am unable to use any of my dungeons until this is fixed. I also have an issue with Boss and death drops, but it might be related.

Yes I am if it is 2-3 days.

**Comment by kangarko** [comment] 2024-09-13 07:02
Understood — will be getting to this today or tomorrow then! You can [see progress here](https://github.com/kangarko/Foundation/commits/v7/) :)

**Comment by kangarko** [comment] 2024-09-14 07:51
Did a test by creating a brand new boss, works on my end:
![Screenshot 2024-09-14 at 09 49 58](https://github.com/user-attachments/assets/0f7af19b-2894-4e97-ac87-33abc8a86b54)

Please use these jars:

[Archive.zip](https://github.com/user-attachments/files/17001495/Archive.zip)

If that does not work, can you please take out the Boss egg from the spawner and try clicking with it on the floor outside of arena where mobs can spawn to see if the Boss still spawns from it? Or left click to see if the menu will pop up.

**Comment by kangarko** [comment] 2024-09-14 07:51
@cobrex1

**Comment by cobrex1** [comment] 2024-09-15 09:00
Morning Matej, I have used the two jars you gave me. Loaded them in and re-booted the server.
I started a dungeon and the bosses spawned as normal zombies. 
I took the egg out the spawner and tp'ed to a wild location and the clicked the egg and the incorrect boss spawned.
Placed a new boss egg in the arena spawn point and the now the correct boss spawns. 
Somewhere in the last two updates, the Area has corrupted the Boss egg data by the looks of it :(

**Comment by cobrex1** [comment] 2024-09-15 12:49
As an update, I change all the bosses in one of my areas and phase one started with the correct bosses, but phase 2 failed to start even though all the bosses were killed in phase one. 

I have 100's of bosses in different arenas and don't fancy having to swap out all the bosses in them. Hopefully you can find what the issue is. Thus happened before on an update to CA and MC-Version, but cannot remember which one :(

**Comment by kangarko** [comment] 2024-09-20 18:52
Apologizes for delay again, do you have the backup please? Can you send it over? I will reproduce with your setup so you don't have to pull more backups or waste time swapping out bosses. Ideally you can zip me the world folder too, if it is too big you can use ufile.io and send via email for privacy.

**Comment by kangarko** [comment] 2024-09-20 18:53
Or, can you just ZIP the entire server? I was not able to reproduce, so I need the exact environment so I can test and fix it asap without having to message back and forth. That would be the best, thanks.

**Comment by cobrex1** [comment] 2024-09-21 13:08
Have sent you an email

**Comment by kangarko** [comment] 2024-09-21 17:36
Closing. Turned out to be a Paper related bug, opened a ticket at theirs: https://github.com/PaperMC/Paper/issues/11423

**Closed by kangarko** 2024-09-21 17:36 UTC
Labels: issue
