### ISSUE TITLE
1.12.2 - Bungee Question

### ISSUE THREAD

**Issue by SkyHazeSB** [kangarko/CoreArena#444] opened 2022-03-03 00:07 UTC
Hey! I was wondering if it was at all possible to setup a bungee server on my 1.12.2 server that’s running 1.16 so I can actually use procedural damage. I didn’t want to make a whole new server just for MA though, I wanted to make it so when a player does the join command on my 1.12 server they get transferred to the 1.16 server into the arena lobby that they joined. If that makes any sense. 

If that’s not possible right now, is there any chance you could make that a possibility? My main appeal to the plugin was the procedural damage and I didn’t find out you needed 1.13+ in order to use it until I already got the plugin.

**Comment by kangarko** [comment] 2022-03-03 06:43
Hey! I do think it should be possible using ProtocolSupport plugin that you install on 1.16 allowing 1.12 clients to join. 

Worst case I could enable procedural damage for <1.13 versions but the issue is the arenas won't get properly restored due to lacking WorldEdit APIs, so they would only get damaged and you'd need to reset your entire world using a third party plugin.

**Comment by kangarko** [comment] 2022-03-03 06:43
Closing, lemme know below if there's anything else I can help you with!

**Closed by kangarko** 2022-03-03 06:43 UTC
Labels: question

**Comment by kangarko** [comment] 2022-03-03 17:38
I do think it's possible since you can place CoreArena on both your main server and the 1.16 game one, and let both servers use the same MySQL database connection so that players' data are transferred.

We do not teleport players automatically back after the game though.

**Comment by SkyHazeSB** [comment] 2022-03-03 17:59
Beautiful, would the plugin know to transfer the player to the arena server after doing the join command in the main one?

Also, do you think it would be possible to send players back to the main server after the arena ends via post game console commands in the config?

I seriously appreciate the help, sorry for being such a hassle.

**Comment by SkyHazeSB** [comment] 2022-03-05 21:18
Hey! We were talking about bungee on Github but the ticket got closed. I
was just wondering if it was still active or not? I still had a couple
questions about it.

Thanks so much for your help, I really love this plugin, I just seriously
want to get the full potential out of it.

**Comment by kangarko** [comment] 2022-03-10 16:53
We can still communicate even if the ticket is closed :)

Players need to join the arena server first and then join the arena manually by typing /ma join or /arena join.

I do think it should be possible to send players back to the main server using a simple API extension listening to our ArenaLeaveEvent. If you have a developer or someone, they can do it quickly. Or players can just switch servers manually.

**Comment by SkyHazeSB** [comment] 2022-03-10 18:17
Awesome! I didn’t know that.

That was my next question as well, I saw those leave and end events at the
bottom of the config and was wondering how to add commands to them. If I
could do that it would allow me to easily transfer players server to server
with /move in bungee. I have everything else figured out except how to move
players back after the game has completed.

Is there a document explaining how to add commands to the game events in
the config?

Really appreciate your help.

**Comment by kangarko** [comment] 2022-03-10 18:22
Hey, yes, please read the documentation above the config file in the # comments:

![a](https://i.imgur.com/pGxOJSn.png)

**Comment by kangarko** [comment] 2022-03-10 19:09
It's fine, just ask away!

**Comment by SkyHazeSB** [comment] 2022-03-15 15:10
Sorry for reviving this, but I just can’t seem to figure out how to add the
@connect <server> command in the events. I’ve tried both in the player
events and console events but nothing works in either.

This is what I tried in my config
https://www.toptal.com/developers/hastebin/omozunekil.less

Is there a certain spot that’s not a player or console event I need to put
that?

Thanks so much for the help

**Comment by kangarko** [comment] 2022-03-20 13:54
Any console errors? Ensure players are connected through bungeecord. Also your hastebin link does not work, please use pastebin.com

**Comment by SkyHazeSB** [comment] 2022-03-23 00:09
I see my problem, the players are joining through my main server by doing /ma (which I have set to /server mobarena). They aren't joining through the bungee server. Is there any way around this? The point of this workaround for me was so I could have a server dedicated to CoreArena off of my main server, so if I need to have the arenas on my main server that players connect to through the bungee server that defeats the purpose haha

**Comment by kangarko** [comment] 2022-04-03 18:51
Sorry for the delay, will be investigating tomorrow!

**Comment by kangarko** [comment] 2022-04-04 09:48
Sorry again for the delay, should be fixed in the next release!

**Comment by SkyHazeSB** [comment] 2022-04-05 00:28
Awesome! Thanks so much!
