### ISSUE TITLE
Mob spawning

### ISSUE THREAD

**Issue by EmmaFromNorway** [kangarko/CoreArena#61] opened 2018-03-23 10:21 UTC
Hey,

After starting the arena and selecting kits the mobs doesn't spawn. I'm not sure if it conflicts with any other plugins or if it's something else. I've followed the tutorial as well but it still doesn't let any of the mobs spawn. What can I do about this?

Thank you for your time reading this.

UltimateTowny

**Comment by BlackGamer000** [comment] 2018-03-23 10:46
Have you tried to set the Difficulty of the Server? i mean the command /difficulty,

**Comment by EmmaFromNorway** [comment] 2018-03-23 10:59
Just tried to set it to easy. The mobs doesn't spawn...

**Comment by BlackGamer000** [comment] 2018-03-23 22:30
Do you Have WorldGuard or Some plugin that blocks The Mob-Spawning? If you have WorldGuard with a Region try to set the Flag mob-spawning: allow 

(Oh and, Sorry for the Intrusion. But i'm just suggest some Ideas to fix the Problem)

**Comment by EmmaFromNorway** [comment] 2018-03-23 23:46
Yup I have it enabeled. Dw you're not interupting

**Comment by kangarko** [comment] 2018-03-25 09:41
Please upload me your data.db file (either ZIP it and drag and drop here or use for example mediafire).

**Comment by EmmaFromNorway** [comment] 2018-03-29 15:18
Sorry for a late reply. Been bust with a film production. It won't let me ZIP it so I put it in a document. Hope this is alright, if not I'll try to use mediafire.

[This file stores various data you create via the plugin.docx](https://github.com/kangarko/CoreArena/files/1860718/This.file.stores.various.data.you.create.via.the.plugin.docx)

**Comment by Techno-Panda** [comment] 2018-04-03 17:33
I know its not my place to comment but might it be your players aren't near the spawners?

**Comment by EmmaFromNorway** [comment] 2018-04-03 20:14
Nope even with a full arena and each player standing on each spawner so dont think it's that

**Comment by kangarko** [comment] 2018-04-06 12:10
What's your MC version?

Also, please check the Mob_Limit setting in your arena .yml file in arenas/, and make sure it's on a higher number like 100.

**Comment by EmmaFromNorway** [comment] 2018-04-06 12:16
The latest 1.12.2 and the moblimit is on a 100

**Comment by Vinyljackers** [comment] 2018-04-06 15:57
I have the same issue on 1.10 no regions with we and not even 1 mob is spawning

**Comment by EmmaFromNorway** [comment] 2018-04-13 21:48
How's it going?

**Comment by kangarko** [comment] 2018-04-17 16:37
I addressed a spawning issue in 1.6.1, forgot to close this issue.

@EmmaFromNorway and @Vinyljackers please test it on that version.

**Comment by EmmaFromNorway** [comment] 2018-05-01 13:16
Yes, also tried to delete the arena and start from scratch

**Comment by kangarko** [comment] 2018-05-16 11:35
@EmmaFromNorway hello and apologies for a late answer, I am sorry to say I was not able to reproduce the bug. From my testing everything works correctly.

One last test I can do is when you upload me your entire CoreArena folder as a ZIP (you can do this easily on windows/mac) and upload it here directly (just drag and drop it to the answer window here), so I can try to reproduce with exactly your settings.

**Comment by kangarko** [comment] 2018-07-12 17:55
If you still have issues please post below.

**Closed by kangarko** 2018-07-12 17:55 UTC
Labels: Issue: complaint, Status: in progress
