### ISSUE TITLE
wither cant fly in Corearena

### ISSUE THREAD

**Issue by Scrulius** [kangarko/CoreArena#348] opened 2020-09-23 21:10 UTC
Paper last version, minecraft 1.16.3

 if you spawn a wither in corearena he cant fly

No console errors.

**Comment by LeehamElectronics** [comment] 2020-09-23 21:14
Please put CoreArena into debug mode using ‘*’ in the settings.yml
Then try running CoreArena and send us your latest.log in Pastebin.

**Comment by Scrulius** [comment] 2020-09-23 21:38
In debug mode if i enter to the arena, the arena end.

https://pastebin.com/YGAkUHAR

**Comment by LeehamElectronics** [comment] 2020-09-23 22:18
Could you send us your arena.yml file for the arena you are testing? Use Pastebin for that too.
Thanks

**Comment by Scrulius** [comment] 2020-09-23 22:29
https://pastebin.com/9KAssSHY

**Comment by kangarko** [comment] 2020-09-24 18:22
Remove MythicMobs and use /corearena egg command to get the egg for it, test that one instead and report to me if it still happens.

**Comment by Scrulius** [comment] 2020-09-24 19:18
Ok, i remove Mythicmobs plugin. Using the corearena Wither egg spawn a sheep 

https://pastebin.com/FpaQDJfJ

**Comment by LeehamElectronics** [comment] 2020-09-25 11:21
Yes I can confirm this issue as well. Hopefully it will be fixed soon.
```
[21:19:37 INFO]: mail2002 issued server command: /ma join test_1
[21:19:42 INFO]: mail2002 issued server command: /ma start
[21:19:42 INFO]: The game in test_1 has begun (1/8)!
[21:19:42 INFO]: [spawning] #-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
[21:19:42 INFO]: [spawning] #-#-#-#-#-# Launching spawners for phase 1 #-#-#-#-#-#
[21:19:42 INFO]: [spawning] 1 ::: Activating Spawner{from 1 phase, 1 ItemStack{SHEEP_SPAWN_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn Wither, lore=[, Place this item in your, monster spawner to, summon Wither], enchants={DURABILITY=1}, ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS]}}}
[21:19:42 INFO]: [spawning]     Found mail2002 in range of 4 blocks from spawner
[21:19:42 INFO]: [spawning]     Selected spawner slot: 1 ItemStack{SHEEP_SPAWN_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn Wither, lore=[, Place this item in your, monster spawner to, summon Wither], enchants={DURABILITY=1}, ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS]}}
[21:19:42 INFO]: [spawning] Trying to spawn boss at MobArena [-44, 5, 241]
[21:19:42 INFO]: [spawning] Spawning boss at MobArena [-44, 5, 241]
[21:19:42 INFO]: [spawning]             SUCCESS spawning SHEEP at MobArena [-44, 5, 241]
```

**Comment by kangarko** [comment] 2020-09-28 17:21
Well after testing I found that yes, indeed SpigotMC somehow nerfs these mobs when spawned through API. Maybe you can test the arena running a command /summon to "naturally" summon Wither to try to fix that. Ensure you test the command manually when not playing arenas first to compare.

**Comment by LeehamElectronics** [comment] 2020-09-28 22:30
I feel like we could bypass this issue if we had the option to run console commands 'per wave' which was actually the very first feature I requested when I got this plugin. If we could simply set a custom command to run on a specified wave such as:

On wave 6 "/summon wither pos"
On wave 10 "/summon with @player"

This would most probably work as a temporary fix, and it would allow us to do all sorts of other cool customisation too.
Thx

**Comment by kangarko** [comment] 2020-10-02 18:39
Oh that's already possible since recently ;)

![a](https://i.imgur.com/atVztMh.png)

**Closed by kangarko** 2020-10-02 18:39 UTC
Labels: issue

**Comment by LeehamElectronics** [comment] 2020-10-02 21:14
Oh sorry didn't even realise, thanks!!
