### ISSUE TITLE
Mobs not spawning properly on phase 1

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#114] opened 2018-07-27 22:47 UTC
Monster spawnpoints do not seem to trigger properly on phase 1, or at least some do and some don't?
I have two `on 1. Phase` spawnpoints set near where my players spawn and are set to spawn zombies with a 100% when there's only 1 player and nothing spawns from them.

**Comment by kangarko** [comment] 2018-07-29 19:05
ZIP me your CoreArena/ folder here please (remember to remove MySQL information).

What arena is that?

**Comment by TheWranger** [comment] 2018-07-30 06:04
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/2239845/CoreArena.zip)
Arena is DAF

**Comment by kangarko** [comment] 2018-07-31 15:08
They are too far away for the spawn mechanism to function. Move spawners closer. Start with 15 blocks' radius and increase. I believe there is an setting for that in spigot.yml but not sure.

**Comment by kangarko** [comment] 2018-08-15 11:05
@TheWranger I honestly apologies for not coming back to you on time. I put this issue to in-progress but overseen it since, my mistake.

Now, I tried to reproduce your environment, but still, all monster spawners were functional as expected.

That is why I added a new debug option to print out all information when a spawner is started. Please set Debug to "[spawning]" in the next release and post the console output when that happens. 

Thank you very much.

**Comment by kangarko** [comment] 2018-08-24 19:11
As a part of general maintenance, I am closing this issue.

When you get to see it, make sure to comment below with the debug option so I can help you quickly this time. Thank you.

**Comment by TheWranger** [comment] 2018-09-20 03:40
@kangarko 
```
19.09 23:35:54 [Server] INFO » Iterating through spawn point: {chance=100, activePeriod={mode=on, limit2=1, limit=1}, minPlayers=1, location=mobarena, 93, 94, 70, spawns=[{count=1, entity=ZOMBIE}]}
19.09 23:35:54 [Server] INFO » Not in range: 40
```
This is what debug is telling me, even though I'm standing within 8 blocks of the spawner when I spawn.

**Comment by kangarko** [comment] 2018-09-27 17:54
@TheWranger sorry for a late reply, I changed that message to be more meaningful.

Sorry for bothering but are you sure that it was the right spawner (see the coordinates x93, y94, z70) ?

**Comment by TheWranger** [comment] 2018-09-27 23:12
Yes, am certain that it was the right spawner.

**Comment by kangarko** [comment] 2018-10-01 15:07
Okay I see, please post the new debug message once it occurs.

**Comment by kangarko** [comment] 2018-10-05 18:41
I am taking initiative on Monday, will have more time so will do thoughful testing. Also taking some of your suggestions from earlier.

**Comment by kangarko** [comment] 2018-10-08 20:17
Sorry I could not reproduce the issue. Do you have a large world? If it is possible, perhaps you can upload it to Google Drive or similar and send me the link in private so I can reproduce using your map, since I have to manually place a new one even when using your config. If not, no problem, we'll find an alternative solution.

PS: For faster communication, you can add me on Discord on kangarko#4233

**Comment by kangarko** [comment] 2018-10-13 07:01
Seems to be working fine on the latest version. Also added some of the requested features from Summer, apologies that it took so long. If anything, you have the new debug option, please use it. Thanks.

**Closed by kangarko** 2018-10-13 07:01 UTC
Labels: Issue: complaint, Status: queued

**Comment by TheWranger** [comment] 2018-11-26 06:43
```
26.11 01:38:28 [Server] INFO » [spawning] Iterating through spawn point: {chance=100, activePeriod={mode=on, limit2=1, limit=1}, minPlayers=1, location=mobarena, 93, 94, 70, spawns=[{count=1, entity=ZOMBIE}]}
26.11 01:38:28 [Server] INFO » [spawning] Player TheWranger is within 80.0874522007037 blocks to spawner
26.11 01:38:28 [Server] INFO » [spawning] Not in range: 48
26.11 01:38:28 [Server] INFO » [spawning] Iterating through spawn point: {chance=100, activePeriod={mode=on, limit2=1, limit=1}, minPlayers=1, location=mobarena, 93, 94, 78, spawns=[{count=1, entity=ZOMBIE}]}
26.11 01:38:28 [Server] INFO » [spawning] Player TheWranger is within 78.77816956492453 blocks to spawner
26.11 01:38:28 [Server] INFO » [spawning] Not in range: 48
2
```
Both of these are within a couple of blocks of where I spawn. I think the issue might be that it's checking the range too early (before I've been teleported and am still in the arena lobby)

**Comment by kangarko** [comment] 2018-11-29 09:15
Fixed!!
